/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/apis/workloads/v1alpha2"
	versioned "sigs.k8s.io/rbgs/api/client-go/clientset/versioned"
	internalinterfaces "sigs.k8s.io/rbgs/api/client-go/informers/externalversions/internalinterfaces"
	v1alpha2 "sigs.k8s.io/rbgs/api/client-go/listers/workloads/v1alpha2"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// RoleBasedGroups returns a RoleBasedGroupInformer.
	RoleBasedGroups() RoleBasedGroupInformer
	// RoleBasedGroupScalingAdapters returns a RoleBasedGroupScalingAdapterInformer.
	RoleBasedGroupScalingAdapters() RoleBasedGroupScalingAdapterInformer
	// RoleBasedGroupSets returns a RoleBasedGroupSetInformer.
	RoleBasedGroupSets() RoleBasedGroupSetInformer
	// RoleInstances returns a RoleInstanceInformer.
	RoleInstances() RoleInstanceInformer
	// RoleInstanceSets returns a RoleInstanceSetInformer.
	RoleInstanceSets() RoleInstanceSetInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// RoleBasedGroupInformer provides access to a shared informer and lister for RoleBasedGroups.
type RoleBasedGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.RoleBasedGroupLister
}

type roleBasedGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

func (f *version) RoleBasedGroups() RoleBasedGroupInformer {
	return &roleBasedGroupInformer{factory: f.factory, namespace: f.namespace, tweakListOptions: f.tweakListOptions}
}

func (f *roleBasedGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if f.tweakListOptions != nil {
					f.tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleBasedGroups(f.namespace).List(nil, options) //nolint:staticcheck
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if f.tweakListOptions != nil {
					f.tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleBasedGroups(f.namespace).Watch(nil, options) //nolint:staticcheck
			},
		},
		&workloadsv1alpha2.RoleBasedGroup{},
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
	)
}

func (f *roleBasedGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&workloadsv1alpha2.RoleBasedGroup{}, f.defaultInformer)
}

func (f *roleBasedGroupInformer) Lister() v1alpha2.RoleBasedGroupLister {
	return v1alpha2.NewRoleBasedGroupLister(f.Informer().GetIndexer())
}

// RoleBasedGroupScalingAdapterInformer provides access to a shared informer and lister.
type RoleBasedGroupScalingAdapterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.RoleBasedGroupScalingAdapterLister
}

type roleBasedGroupScalingAdapterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

func (f *version) RoleBasedGroupScalingAdapters() RoleBasedGroupScalingAdapterInformer {
	return &roleBasedGroupScalingAdapterInformer{factory: f.factory, namespace: f.namespace, tweakListOptions: f.tweakListOptions}
}

func (f *roleBasedGroupScalingAdapterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if f.tweakListOptions != nil {
					f.tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleBasedGroupScalingAdapters(f.namespace).List(nil, options) //nolint:staticcheck
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if f.tweakListOptions != nil {
					f.tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleBasedGroupScalingAdapters(f.namespace).Watch(nil, options) //nolint:staticcheck
			},
		},
		&workloadsv1alpha2.RoleBasedGroupScalingAdapter{},
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
	)
}

func (f *roleBasedGroupScalingAdapterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&workloadsv1alpha2.RoleBasedGroupScalingAdapter{}, f.defaultInformer)
}

func (f *roleBasedGroupScalingAdapterInformer) Lister() v1alpha2.RoleBasedGroupScalingAdapterLister {
	return v1alpha2.NewRoleBasedGroupScalingAdapterLister(f.Informer().GetIndexer())
}

// RoleBasedGroupSetInformer provides access to a shared informer and lister.
type RoleBasedGroupSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.RoleBasedGroupSetLister
}

type roleBasedGroupSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

func (f *version) RoleBasedGroupSets() RoleBasedGroupSetInformer {
	return &roleBasedGroupSetInformer{factory: f.factory, namespace: f.namespace, tweakListOptions: f.tweakListOptions}
}

func (f *roleBasedGroupSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if f.tweakListOptions != nil {
					f.tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleBasedGroupSets(f.namespace).List(nil, options) //nolint:staticcheck
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if f.tweakListOptions != nil {
					f.tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleBasedGroupSets(f.namespace).Watch(nil, options) //nolint:staticcheck
			},
		},
		&workloadsv1alpha2.RoleBasedGroupSet{},
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
	)
}

func (f *roleBasedGroupSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&workloadsv1alpha2.RoleBasedGroupSet{}, f.defaultInformer)
}

func (f *roleBasedGroupSetInformer) Lister() v1alpha2.RoleBasedGroupSetLister {
	return v1alpha2.NewRoleBasedGroupSetLister(f.Informer().GetIndexer())
}

// RoleInstanceInformer provides access to a shared informer and lister.
type RoleInstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.RoleInstanceLister
}

type roleInstanceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

func (f *version) RoleInstances() RoleInstanceInformer {
	return &roleInstanceInformer{factory: f.factory, namespace: f.namespace, tweakListOptions: f.tweakListOptions}
}

func (f *roleInstanceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if f.tweakListOptions != nil {
					f.tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleInstances(f.namespace).List(nil, options) //nolint:staticcheck
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if f.tweakListOptions != nil {
					f.tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleInstances(f.namespace).Watch(nil, options) //nolint:staticcheck
			},
		},
		&workloadsv1alpha2.RoleInstance{},
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
	)
}

func (f *roleInstanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&workloadsv1alpha2.RoleInstance{}, f.defaultInformer)
}

func (f *roleInstanceInformer) Lister() v1alpha2.RoleInstanceLister {
	return v1alpha2.NewRoleInstanceLister(f.Informer().GetIndexer())
}

// RoleInstanceSetInformer provides access to a shared informer and lister.
type RoleInstanceSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.RoleInstanceSetLister
}

type roleInstanceSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

func (f *version) RoleInstanceSets() RoleInstanceSetInformer {
	return &roleInstanceSetInformer{factory: f.factory, namespace: f.namespace, tweakListOptions: f.tweakListOptions}
}

func (f *roleInstanceSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if f.tweakListOptions != nil {
					f.tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleInstanceSets(f.namespace).List(nil, options) //nolint:staticcheck
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if f.tweakListOptions != nil {
					f.tweakListOptions(&options)
				}
				return client.WorkloadsV1alpha2().RoleInstanceSets(f.namespace).Watch(nil, options) //nolint:staticcheck
			},
		},
		&workloadsv1alpha2.RoleInstanceSet{},
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
	)
}

func (f *roleInstanceSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&workloadsv1alpha2.RoleInstanceSet{}, f.defaultInformer)
}

func (f *roleInstanceSetInformer) Lister() v1alpha2.RoleInstanceSetLister {
	return v1alpha2.NewRoleInstanceSetLister(f.Informer().GetIndexer())
}
