/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	cache "k8s.io/client-go/tools/cache"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/apis/workloads/v1alpha1"
)

// RoleBasedGroupLister helps list RoleBasedGroups.
// All objects returned here must be treated as read-only.
type RoleBasedGroupLister interface {
	// List lists all RoleBasedGroups in the indexer.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroup, err error)
	// RoleBasedGroups returns an object that can list and get RoleBasedGroups.
	RoleBasedGroups(namespace string) RoleBasedGroupNamespaceLister
}

// RoleBasedGroupNamespaceLister helps list and get RoleBasedGroups.
// All objects returned here must be treated as read-only.
type RoleBasedGroupNamespaceLister interface {
	// List lists all RoleBasedGroups in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroup, err error)
	// Get retrieves the RoleBasedGroup from the indexer for a given namespace and name.
	Get(name string) (*workloadsv1alpha1.RoleBasedGroup, error)
}

type roleBasedGroupLister struct {
	indexer cache.Indexer
}

// NewRoleBasedGroupLister returns a new RoleBasedGroupLister.
func NewRoleBasedGroupLister(indexer cache.Indexer) RoleBasedGroupLister {
	return &roleBasedGroupLister{indexer: indexer}
}

func (s *roleBasedGroupLister) List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroup, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*workloadsv1alpha1.RoleBasedGroup))
	})
	return ret, err
}

func (s *roleBasedGroupLister) RoleBasedGroups(namespace string) RoleBasedGroupNamespaceLister {
	return roleBasedGroupNamespaceLister{indexer: s.indexer, namespace: namespace}
}

type roleBasedGroupNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

func (s roleBasedGroupNamespaceLister) List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroup, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*workloadsv1alpha1.RoleBasedGroup))
	})
	return ret, err
}

func (s roleBasedGroupNamespaceLister) Get(name string) (*workloadsv1alpha1.RoleBasedGroup, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, cache.ErrResourceVersionNotFound
	}
	return obj.(*workloadsv1alpha1.RoleBasedGroup), nil
}

// RoleBasedGroupSetLister helps list RoleBasedGroupSets.
type RoleBasedGroupSetLister interface {
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupSet, err error)
	RoleBasedGroupSets(namespace string) RoleBasedGroupSetNamespaceLister
}

// RoleBasedGroupSetNamespaceLister helps list and get RoleBasedGroupSets.
type RoleBasedGroupSetNamespaceLister interface {
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupSet, err error)
	Get(name string) (*workloadsv1alpha1.RoleBasedGroupSet, error)
}

type roleBasedGroupSetLister struct {
	indexer cache.Indexer
}

// NewRoleBasedGroupSetLister returns a new RoleBasedGroupSetLister.
func NewRoleBasedGroupSetLister(indexer cache.Indexer) RoleBasedGroupSetLister {
	return &roleBasedGroupSetLister{indexer: indexer}
}

func (s *roleBasedGroupSetLister) List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupSet, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*workloadsv1alpha1.RoleBasedGroupSet))
	})
	return ret, err
}

func (s *roleBasedGroupSetLister) RoleBasedGroupSets(namespace string) RoleBasedGroupSetNamespaceLister {
	return roleBasedGroupSetNamespaceLister{indexer: s.indexer, namespace: namespace}
}

type roleBasedGroupSetNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

func (s roleBasedGroupSetNamespaceLister) List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupSet, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*workloadsv1alpha1.RoleBasedGroupSet))
	})
	return ret, err
}

func (s roleBasedGroupSetNamespaceLister) Get(name string) (*workloadsv1alpha1.RoleBasedGroupSet, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, cache.ErrResourceVersionNotFound
	}
	return obj.(*workloadsv1alpha1.RoleBasedGroupSet), nil
}

// RoleBasedGroupScalingAdapterLister helps list RoleBasedGroupScalingAdapters.
type RoleBasedGroupScalingAdapterLister interface {
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupScalingAdapter, err error)
	RoleBasedGroupScalingAdapters(namespace string) RoleBasedGroupScalingAdapterNamespaceLister
}

// RoleBasedGroupScalingAdapterNamespaceLister helps list and get RoleBasedGroupScalingAdapters.
type RoleBasedGroupScalingAdapterNamespaceLister interface {
	List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupScalingAdapter, err error)
	Get(name string) (*workloadsv1alpha1.RoleBasedGroupScalingAdapter, error)
}

type roleBasedGroupScalingAdapterLister struct {
	indexer cache.Indexer
}

// NewRoleBasedGroupScalingAdapterLister returns a new RoleBasedGroupScalingAdapterLister.
func NewRoleBasedGroupScalingAdapterLister(indexer cache.Indexer) RoleBasedGroupScalingAdapterLister {
	return &roleBasedGroupScalingAdapterLister{indexer: indexer}
}

func (s *roleBasedGroupScalingAdapterLister) List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupScalingAdapter, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*workloadsv1alpha1.RoleBasedGroupScalingAdapter))
	})
	return ret, err
}

func (s *roleBasedGroupScalingAdapterLister) RoleBasedGroupScalingAdapters(namespace string) RoleBasedGroupScalingAdapterNamespaceLister {
	return roleBasedGroupScalingAdapterNamespaceLister{indexer: s.indexer, namespace: namespace}
}

type roleBasedGroupScalingAdapterNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

func (s roleBasedGroupScalingAdapterNamespaceLister) List(selector labels.Selector) (ret []*workloadsv1alpha1.RoleBasedGroupScalingAdapter, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*workloadsv1alpha1.RoleBasedGroupScalingAdapter))
	})
	return ret, err
}

func (s roleBasedGroupScalingAdapterNamespaceLister) Get(name string) (*workloadsv1alpha1.RoleBasedGroupScalingAdapter, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, cache.ErrResourceVersionNotFound
	}
	return obj.(*workloadsv1alpha1.RoleBasedGroupScalingAdapter), nil
}
