/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/apis/workloads/v1alpha1"
	scheme "sigs.k8s.io/rbgs/api/client-go/clientset/versioned/scheme"
)

// RoleBasedGroupsGetter has a method to return a RoleBasedGroupInterface.
type RoleBasedGroupsGetter interface {
	RoleBasedGroups(namespace string) RoleBasedGroupInterface
}

// RoleBasedGroupInterface has methods to work with RoleBasedGroup resources.
type RoleBasedGroupInterface interface {
	Create(ctx context.Context, obj *workloadsv1alpha1.RoleBasedGroup, opts v1.CreateOptions) (*workloadsv1alpha1.RoleBasedGroup, error)
	Update(ctx context.Context, obj *workloadsv1alpha1.RoleBasedGroup, opts v1.UpdateOptions) (*workloadsv1alpha1.RoleBasedGroup, error)
	UpdateStatus(ctx context.Context, obj *workloadsv1alpha1.RoleBasedGroup, opts v1.UpdateOptions) (*workloadsv1alpha1.RoleBasedGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha1.RoleBasedGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha1.RoleBasedGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha1.RoleBasedGroup, err error)
	RoleBasedGroupExpansion
}

type roleBasedGroups struct {
	*gentype.ClientWithList[*workloadsv1alpha1.RoleBasedGroup, *workloadsv1alpha1.RoleBasedGroupList]
}

func newRoleBasedGroups(c *WorkloadsV1alpha1Client, namespace string) *roleBasedGroups {
	return &roleBasedGroups{
		gentype.NewClientWithList[*workloadsv1alpha1.RoleBasedGroup, *workloadsv1alpha1.RoleBasedGroupList](
			"rolebasedgroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha1.RoleBasedGroup { return &workloadsv1alpha1.RoleBasedGroup{} },
			func() *workloadsv1alpha1.RoleBasedGroupList { return &workloadsv1alpha1.RoleBasedGroupList{} },
		),
	}
}

// RoleBasedGroupSetsGetter has a method to return a RoleBasedGroupSetInterface.
type RoleBasedGroupSetsGetter interface {
	RoleBasedGroupSets(namespace string) RoleBasedGroupSetInterface
}

// RoleBasedGroupSetInterface has methods to work with RoleBasedGroupSet resources.
type RoleBasedGroupSetInterface interface {
	Create(ctx context.Context, obj *workloadsv1alpha1.RoleBasedGroupSet, opts v1.CreateOptions) (*workloadsv1alpha1.RoleBasedGroupSet, error)
	Update(ctx context.Context, obj *workloadsv1alpha1.RoleBasedGroupSet, opts v1.UpdateOptions) (*workloadsv1alpha1.RoleBasedGroupSet, error)
	UpdateStatus(ctx context.Context, obj *workloadsv1alpha1.RoleBasedGroupSet, opts v1.UpdateOptions) (*workloadsv1alpha1.RoleBasedGroupSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha1.RoleBasedGroupSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha1.RoleBasedGroupSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha1.RoleBasedGroupSet, err error)
	RoleBasedGroupSetExpansion
}

type roleBasedGroupSets struct {
	*gentype.ClientWithList[*workloadsv1alpha1.RoleBasedGroupSet, *workloadsv1alpha1.RoleBasedGroupSetList]
}

func newRoleBasedGroupSets(c *WorkloadsV1alpha1Client, namespace string) *roleBasedGroupSets {
	return &roleBasedGroupSets{
		gentype.NewClientWithList[*workloadsv1alpha1.RoleBasedGroupSet, *workloadsv1alpha1.RoleBasedGroupSetList](
			"rolebasedgroupsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha1.RoleBasedGroupSet { return &workloadsv1alpha1.RoleBasedGroupSet{} },
			func() *workloadsv1alpha1.RoleBasedGroupSetList { return &workloadsv1alpha1.RoleBasedGroupSetList{} },
		),
	}
}

// RoleBasedGroupScalingAdaptersGetter has a method to return a RoleBasedGroupScalingAdapterInterface.
type RoleBasedGroupScalingAdaptersGetter interface {
	RoleBasedGroupScalingAdapters(namespace string) RoleBasedGroupScalingAdapterInterface
}

// RoleBasedGroupScalingAdapterInterface has methods to work with RoleBasedGroupScalingAdapter resources.
type RoleBasedGroupScalingAdapterInterface interface {
	Create(ctx context.Context, obj *workloadsv1alpha1.RoleBasedGroupScalingAdapter, opts v1.CreateOptions) (*workloadsv1alpha1.RoleBasedGroupScalingAdapter, error)
	Update(ctx context.Context, obj *workloadsv1alpha1.RoleBasedGroupScalingAdapter, opts v1.UpdateOptions) (*workloadsv1alpha1.RoleBasedGroupScalingAdapter, error)
	UpdateStatus(ctx context.Context, obj *workloadsv1alpha1.RoleBasedGroupScalingAdapter, opts v1.UpdateOptions) (*workloadsv1alpha1.RoleBasedGroupScalingAdapter, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha1.RoleBasedGroupScalingAdapter, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha1.RoleBasedGroupScalingAdapterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha1.RoleBasedGroupScalingAdapter, err error)
	RoleBasedGroupScalingAdapterExpansion
}

type roleBasedGroupScalingAdapters struct {
	*gentype.ClientWithList[*workloadsv1alpha1.RoleBasedGroupScalingAdapter, *workloadsv1alpha1.RoleBasedGroupScalingAdapterList]
}

func newRoleBasedGroupScalingAdapters(c *WorkloadsV1alpha1Client, namespace string) *roleBasedGroupScalingAdapters {
	return &roleBasedGroupScalingAdapters{
		gentype.NewClientWithList[*workloadsv1alpha1.RoleBasedGroupScalingAdapter, *workloadsv1alpha1.RoleBasedGroupScalingAdapterList](
			"rolebasedgroupscalingadapters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha1.RoleBasedGroupScalingAdapter {
				return &workloadsv1alpha1.RoleBasedGroupScalingAdapter{}
			},
			func() *workloadsv1alpha1.RoleBasedGroupScalingAdapterList {
				return &workloadsv1alpha1.RoleBasedGroupScalingAdapterList{}
			},
		),
	}
}
