/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	rest "k8s.io/client-go/rest"
	workloadsv1alpha1 "sigs.k8s.io/rbgs/api/apis/workloads/v1alpha1"
	scheme "sigs.k8s.io/rbgs/api/client-go/clientset/versioned/scheme"
)

// WorkloadsV1alpha1Interface defines the methods for the v1alpha1 workloads client.
type WorkloadsV1alpha1Interface interface {
	RESTClient() rest.Interface
	RoleBasedGroupsGetter
	RoleBasedGroupScalingAdaptersGetter
	RoleBasedGroupSetsGetter
}

// WorkloadsV1alpha1Client is used to interact with features provided by the workloads.x-k8s.io group.
type WorkloadsV1alpha1Client struct {
	restClient rest.Interface
}

// RoleBasedGroups returns a RoleBasedGroupInterface for a given namespace.
func (c *WorkloadsV1alpha1Client) RoleBasedGroups(namespace string) RoleBasedGroupInterface {
	return newRoleBasedGroups(c, namespace)
}

// RoleBasedGroupScalingAdapters returns a RoleBasedGroupScalingAdapterInterface for a given namespace.
func (c *WorkloadsV1alpha1Client) RoleBasedGroupScalingAdapters(namespace string) RoleBasedGroupScalingAdapterInterface {
	return newRoleBasedGroupScalingAdapters(c, namespace)
}

// RoleBasedGroupSets returns a RoleBasedGroupSetInterface for a given namespace.
func (c *WorkloadsV1alpha1Client) RoleBasedGroupSets(namespace string) RoleBasedGroupSetInterface {
	return newRoleBasedGroupSets(c, namespace)
}

// NewForConfig creates a new WorkloadsV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*WorkloadsV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new WorkloadsV1alpha1Client for the given config and http client.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*WorkloadsV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &WorkloadsV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new WorkloadsV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *WorkloadsV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new WorkloadsV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *WorkloadsV1alpha1Client {
	return &WorkloadsV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := workloadsv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *WorkloadsV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
