/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

// RoleBasedGroupExpansion is the interface for expansion of RoleBasedGroup clients.
type RoleBasedGroupExpansion interface{}

// RoleBasedGroupSetExpansion is the interface for expansion of RoleBasedGroupSet clients.
type RoleBasedGroupSetExpansion interface{}

// RoleBasedGroupScalingAdapterExpansion is the interface for expansion of RoleBasedGroupScalingAdapter clients.
type RoleBasedGroupScalingAdapterExpansion interface{}

// RoleInstanceExpansion is the interface for expansion of RoleInstance clients.
type RoleInstanceExpansion interface{}

// RoleInstanceSetExpansion is the interface for expansion of RoleInstanceSet clients.
type RoleInstanceSetExpansion interface{}
