/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	workloadsv1alpha2 "sigs.k8s.io/rbgs/api/apis/workloads/v1alpha2"
	scheme "sigs.k8s.io/rbgs/api/client-go/clientset/versioned/scheme"
)

// RoleBasedGroupsGetter has a method to return a RoleBasedGroupInterface.
type RoleBasedGroupsGetter interface {
	RoleBasedGroups(namespace string) RoleBasedGroupInterface
}

// RoleBasedGroupInterface has methods to work with RoleBasedGroup resources.
type RoleBasedGroupInterface interface {
	Create(ctx context.Context, roleBasedGroup *workloadsv1alpha2.RoleBasedGroup, opts v1.CreateOptions) (*workloadsv1alpha2.RoleBasedGroup, error)
	Update(ctx context.Context, roleBasedGroup *workloadsv1alpha2.RoleBasedGroup, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleBasedGroup, error)
	UpdateStatus(ctx context.Context, roleBasedGroup *workloadsv1alpha2.RoleBasedGroup, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleBasedGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha2.RoleBasedGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha2.RoleBasedGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha2.RoleBasedGroup, err error)
	RoleBasedGroupExpansion
}

// roleBasedGroups implements RoleBasedGroupInterface.
type roleBasedGroups struct {
	*gentype.ClientWithList[*workloadsv1alpha2.RoleBasedGroup, *workloadsv1alpha2.RoleBasedGroupList]
}

// newRoleBasedGroups returns a RoleBasedGroups.
func newRoleBasedGroups(c *WorkloadsV1alpha2Client, namespace string) *roleBasedGroups {
	return &roleBasedGroups{
		gentype.NewClientWithList[*workloadsv1alpha2.RoleBasedGroup, *workloadsv1alpha2.RoleBasedGroupList](
			"rolebasedgroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha2.RoleBasedGroup { return &workloadsv1alpha2.RoleBasedGroup{} },
			func() *workloadsv1alpha2.RoleBasedGroupList { return &workloadsv1alpha2.RoleBasedGroupList{} },
		),
	}
}

// RoleBasedGroupSetsGetter has a method to return a RoleBasedGroupSetInterface.
type RoleBasedGroupSetsGetter interface {
	RoleBasedGroupSets(namespace string) RoleBasedGroupSetInterface
}

// RoleBasedGroupSetInterface has methods to work with RoleBasedGroupSet resources.
type RoleBasedGroupSetInterface interface {
	Create(ctx context.Context, roleBasedGroupSet *workloadsv1alpha2.RoleBasedGroupSet, opts v1.CreateOptions) (*workloadsv1alpha2.RoleBasedGroupSet, error)
	Update(ctx context.Context, roleBasedGroupSet *workloadsv1alpha2.RoleBasedGroupSet, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleBasedGroupSet, error)
	UpdateStatus(ctx context.Context, roleBasedGroupSet *workloadsv1alpha2.RoleBasedGroupSet, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleBasedGroupSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha2.RoleBasedGroupSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha2.RoleBasedGroupSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha2.RoleBasedGroupSet, err error)
	RoleBasedGroupSetExpansion
}

// roleBasedGroupSets implements RoleBasedGroupSetInterface.
type roleBasedGroupSets struct {
	*gentype.ClientWithList[*workloadsv1alpha2.RoleBasedGroupSet, *workloadsv1alpha2.RoleBasedGroupSetList]
}

// newRoleBasedGroupSets returns a RoleBasedGroupSets.
func newRoleBasedGroupSets(c *WorkloadsV1alpha2Client, namespace string) *roleBasedGroupSets {
	return &roleBasedGroupSets{
		gentype.NewClientWithList[*workloadsv1alpha2.RoleBasedGroupSet, *workloadsv1alpha2.RoleBasedGroupSetList](
			"rolebasedgroupsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha2.RoleBasedGroupSet { return &workloadsv1alpha2.RoleBasedGroupSet{} },
			func() *workloadsv1alpha2.RoleBasedGroupSetList { return &workloadsv1alpha2.RoleBasedGroupSetList{} },
		),
	}
}

// RoleBasedGroupScalingAdaptersGetter has a method to return a RoleBasedGroupScalingAdapterInterface.
type RoleBasedGroupScalingAdaptersGetter interface {
	RoleBasedGroupScalingAdapters(namespace string) RoleBasedGroupScalingAdapterInterface
}

// RoleBasedGroupScalingAdapterInterface has methods to work with RoleBasedGroupScalingAdapter resources.
type RoleBasedGroupScalingAdapterInterface interface {
	Create(ctx context.Context, obj *workloadsv1alpha2.RoleBasedGroupScalingAdapter, opts v1.CreateOptions) (*workloadsv1alpha2.RoleBasedGroupScalingAdapter, error)
	Update(ctx context.Context, obj *workloadsv1alpha2.RoleBasedGroupScalingAdapter, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleBasedGroupScalingAdapter, error)
	UpdateStatus(ctx context.Context, obj *workloadsv1alpha2.RoleBasedGroupScalingAdapter, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleBasedGroupScalingAdapter, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha2.RoleBasedGroupScalingAdapter, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha2.RoleBasedGroupScalingAdapterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha2.RoleBasedGroupScalingAdapter, err error)
	RoleBasedGroupScalingAdapterExpansion
}

// roleBasedGroupScalingAdapters implements RoleBasedGroupScalingAdapterInterface.
type roleBasedGroupScalingAdapters struct {
	*gentype.ClientWithList[*workloadsv1alpha2.RoleBasedGroupScalingAdapter, *workloadsv1alpha2.RoleBasedGroupScalingAdapterList]
}

// newRoleBasedGroupScalingAdapters returns a RoleBasedGroupScalingAdapters.
func newRoleBasedGroupScalingAdapters(c *WorkloadsV1alpha2Client, namespace string) *roleBasedGroupScalingAdapters {
	return &roleBasedGroupScalingAdapters{
		gentype.NewClientWithList[*workloadsv1alpha2.RoleBasedGroupScalingAdapter, *workloadsv1alpha2.RoleBasedGroupScalingAdapterList](
			"rolebasedgroupscalingadapters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha2.RoleBasedGroupScalingAdapter {
				return &workloadsv1alpha2.RoleBasedGroupScalingAdapter{}
			},
			func() *workloadsv1alpha2.RoleBasedGroupScalingAdapterList {
				return &workloadsv1alpha2.RoleBasedGroupScalingAdapterList{}
			},
		),
	}
}

// RoleInstancesGetter has a method to return a RoleInstanceInterface.
type RoleInstancesGetter interface {
	RoleInstances(namespace string) RoleInstanceInterface
}

// RoleInstanceInterface has methods to work with RoleInstance resources.
type RoleInstanceInterface interface {
	Create(ctx context.Context, obj *workloadsv1alpha2.RoleInstance, opts v1.CreateOptions) (*workloadsv1alpha2.RoleInstance, error)
	Update(ctx context.Context, obj *workloadsv1alpha2.RoleInstance, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleInstance, error)
	UpdateStatus(ctx context.Context, obj *workloadsv1alpha2.RoleInstance, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleInstance, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha2.RoleInstance, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha2.RoleInstanceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha2.RoleInstance, err error)
	RoleInstanceExpansion
}

// roleInstances implements RoleInstanceInterface.
type roleInstances struct {
	*gentype.ClientWithList[*workloadsv1alpha2.RoleInstance, *workloadsv1alpha2.RoleInstanceList]
}

// newRoleInstances returns a RoleInstances.
func newRoleInstances(c *WorkloadsV1alpha2Client, namespace string) *roleInstances {
	return &roleInstances{
		gentype.NewClientWithList[*workloadsv1alpha2.RoleInstance, *workloadsv1alpha2.RoleInstanceList](
			"roleinstances",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha2.RoleInstance { return &workloadsv1alpha2.RoleInstance{} },
			func() *workloadsv1alpha2.RoleInstanceList { return &workloadsv1alpha2.RoleInstanceList{} },
		),
	}
}

// RoleInstanceSetsGetter has a method to return a RoleInstanceSetInterface.
type RoleInstanceSetsGetter interface {
	RoleInstanceSets(namespace string) RoleInstanceSetInterface
}

// RoleInstanceSetInterface has methods to work with RoleInstanceSet resources.
type RoleInstanceSetInterface interface {
	Create(ctx context.Context, obj *workloadsv1alpha2.RoleInstanceSet, opts v1.CreateOptions) (*workloadsv1alpha2.RoleInstanceSet, error)
	Update(ctx context.Context, obj *workloadsv1alpha2.RoleInstanceSet, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleInstanceSet, error)
	UpdateStatus(ctx context.Context, obj *workloadsv1alpha2.RoleInstanceSet, opts v1.UpdateOptions) (*workloadsv1alpha2.RoleInstanceSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadsv1alpha2.RoleInstanceSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadsv1alpha2.RoleInstanceSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadsv1alpha2.RoleInstanceSet, err error)
	RoleInstanceSetExpansion
}

// roleInstanceSets implements RoleInstanceSetInterface.
type roleInstanceSets struct {
	*gentype.ClientWithList[*workloadsv1alpha2.RoleInstanceSet, *workloadsv1alpha2.RoleInstanceSetList]
}

// newRoleInstanceSets returns a RoleInstanceSets.
func newRoleInstanceSets(c *WorkloadsV1alpha2Client, namespace string) *roleInstanceSets {
	return &roleInstanceSets{
		gentype.NewClientWithList[*workloadsv1alpha2.RoleInstanceSet, *workloadsv1alpha2.RoleInstanceSetList](
			"roleinstancesets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadsv1alpha2.RoleInstanceSet { return &workloadsv1alpha2.RoleInstanceSet{} },
			func() *workloadsv1alpha2.RoleInstanceSetList { return &workloadsv1alpha2.RoleInstanceSetList{} },
		),
	}
}
